dependencies:
  - name: rabbitmq-ha
    version: 1.36.4
    repository: https://github.com/rahulparihar270992/charts
    condition: rabbitmq-ha.enabled
  - name: mongodb-replicaset
    version: 3.9.6
    repository: https://github.com/rahulparihar270992/charts
    alias: mongodb-ha
    condition: mongodb-ha.enabled
  - name: external-dns
    version: 1.6.1
    repository: https://github.com/rahulparihar270992/charts
    condition: external-dns.enabled
  - name: etcd-operator
    version: 0.10.0
    repository: https://github.com/rahulparihar270992/charts
